### PR TITLE
Fixed tabbing

### LINKED ISSUE #451: After Web Clipper invocation, immediate tabbing into the iframe does not work on microsoft.com
1) Go to microsoft.com
2) Invoke the clipper on any browser
3) Hit 'tab' button

**Expected:** The lowest tabIndex element in the iframe is selected
**Actual:** Something else was selected

This is likely due to something on the page wrestling away control from our tab listener.

### PR DESCRIPTION
**Pull request by mttwc**
http://webaim.org/techniques/keyboard/tabindex

Tabindex of 0 does not adhere to the ordering of tabindex > 1 and onwards, so the lowest tabindex we can use is 1, not 0. 

Fixes #451

### CODE REVIEW

**Comment by mttwc** [comment]
Oops, forgot to add UTs. Will add them in a sec.

File: src/scripts/clipperUI/panels/optionsPanel.tsx [hunk 1]
```diff
@@ -30,7 +30,7 @@ class OptionsPanelClass extends ComponentBase<{ }, OptionsPanelProps> {
 
 				<div id={Constants.Ids.clipButtonContainer} className="wideButtonContainer">
 					{clipButtonEnabled
-					?	<a id={Constants.Ids.clipButton} className="wideActionButton" {...this.enableInvoke(this.props.onStartClip, 0) }>
+					?	<a id={Constants.Ids.clipButton} className="wideActionButton" {...this.enableInvoke(this.props.onStartClip, 1) }>
```
Comment (iconix) [inline src/scripts/clipperUI/panels/optionsPanel.tsx]: I assumed when Dipak made this tab index 0, it was because there was already a 1 and he didn't feel like bumping all the other tab indices down :P Not true?

Comment (mttwc) [inline src/scripts/clipperUI/panels/optionsPanel.tsx]: Nope, this is not the case, he made the change to 0 as he thought it was the lowest viable number. Turns out it's 1!

With our tabbing, to avoid huge refactors when changing tab orders, we start each grouping at a multiple of 10, rather than having one directly after the previous (e.g., 1, 2, 3, ... 55, 56, 57 etc)

Comment (iconix) [inline src/scripts/clipperUI/panels/optionsPanel.tsx]: kewl :)

**Comment by iconix** [comment]
:sheep:

**Comment by leakymemory** [comment]
:+1:
