### PR TITLE
Fix blank image recognition race condition

### LINKED ISSUE #50: USA Today page Augmentation API call is successful, but Article preview shows endless spinner
http://www.usatoday.com/story/news/nation/2016/09/22/state-emergency-charlotte-protests-continue-second-night/90825016/

### PR DESCRIPTION
**Pull request by mttwc**
Fixes #50

### CODE REVIEW

File: src/scripts/domParsers/domUtils.ts [hunk 1]
```diff
@@ -372,6 +371,8 @@ export module DomUtils {
 				theImg.onerror = () => {
 					resolve(undefined);
 				};
+
+				theImg.src = img.src;
```
Comment (leakymemory) [inline src/scripts/domParsers/domUtils.ts:376]: Do you think that it's worth a comment here noting the importance of setting the src property _after_ everything else?

**Comment by leakymemory** [comment]
Interesting.  Looks good.

File: src/scripts/domParsers/domUtils.ts (hunk 1 above)
Comment (mttwc) [reply src/scripts/domParsers/domUtils.ts:376]: Good idea. Will add it in.
