### PR TITLE
[Bug] Extract embedded YouTube videos on KhanAcademy pages

### LINKED ISSUE #3: KhanAcademy embedded videos are not being extracted
We will likely need to add some KhanAcademy-specific client-side code to manually extract videos from KhanAcademy.

Also, it would be nice if we can have a folder of scripts that does each of these site-specific extractions, one site per file.

### PR DESCRIPTION
**Pull request by VishaalK**
We use a RegExp to check for the YouTube video ID in the `pageContent`, and insert an iframe with that ID.

Fixes #3

### CODE REVIEW

File: src/scripts/domParsers/videoUtils.ts [hunk 1]
```diff
@@ -21,7 +22,7 @@ export module VideoUtils {
 		let hostname = Utils.getHostname(pageUrl);
 
 		for (let domain in SupportedVideoDomains) {
-			if (typeof(domain) === "string" && hostname.indexOf(domain.toLowerCase() + ".") > -1) {
+			if (typeof (domain) === "string" && hostname.indexOf(domain.toLowerCase() + ".") > -1) {
```
Comment (leakymemory) [inline src/scripts/domParsers/videoUtils.ts]: `typeof domain`?

File: src/scripts/domParsers/videoUtils.ts [hunk 2]
```diff
@@ -65,6 +67,23 @@ export module VideoUtils {
 		return values;
 	}
 
+	export function getKhanAcademyVideoSrcValue(pageContent: string): string {
```
Comment (leakymemory) [inline src/scripts/domParsers/videoUtils.ts]: I realize that we're not consistent through the codebase, but we should use method header comments to at least keep this file looking good. :-)

Note that this is true for the other two new functions below as well.

**Comment by leakymemory** [comment]
Nice job.  I'm glad to see plugging into new sites is so straight forward. 👍

File: src/scripts/domParsers/videoUtils.ts [hunk 3]
```diff
@@ -6,7 +6,8 @@ export module VideoUtils {
 
 	export enum SupportedVideoDomains {
```
Comment (mttwc) [inline src/scripts/domParsers/videoUtils.ts:10]: Currently, all of our domain-specific video-grabbing logic lives in videoUtils, and we use subtly different ways to extract videos from each differing domain, but the end purpose is still the same. I wonder if we can break this up further into smaller classes to make things a bit simpler.

File: src/tests/domParsers/khanAcademyVideo_tests.ts [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+	"<div data-youtubeid=\"video_8-5DTsl1V5k\"> </div>" // double quotations
+];
+
+let pageContentWithMultipleHyphenatedVideoIds = [
+	"<div id='video_8-5DTsl1V5k'></div> <DIV ID='video_8-53sl1V5k'></DIV> <div id='video_4ba196611'> </div>",
+];
+
+QUnit.module("videoUtils");
+
+test("videoDomainIfSupported", () => {
```
Comment (mttwc) [inline src/tests/domParsers/khanAcademyVideo_tests.ts]: The test name should be fleshed out so that if it fails, the person reading the console will know immediately what is going on

File: src/tests/domParsers/khanAcademyVideo_tests.ts [hunk 5]
```diff
@@ -0,0 +1,102 @@
+/// <reference path="../../../typings/main/ambient/qunit/qunit.d.ts" />
+
+import {VideoUtils} from "../../scripts/domParsers/videoUtils";
```
Comment (mttwc) [inline src/tests/domParsers/khanAcademyVideo_tests.ts]: See above comment about splitting up the different domain-specific logics into different class (perhaps implementations of an interface). We can then split the test files up into smaller ones as well. Generally, we want files and their matching test-files to be a 1:1 ratio.

**Comment by mttwc** [comment]
Some comments above. To make things simpler and more scalable, I think videoUtils should be split up into 3 classes, one for each of the domains we're supporting, and have them implement an interface of some sort.

**Comment by VishaalK** [comment]
I'll see how much effort re-organization would take. I'm not sure it is worth it. The API only supports YouTube/Vimeo and these are the big few sites with those embedded right now.

File: src/scripts/domParsers/youtubeVideoExtractor.ts [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+		let youTubeId;
+		if (Utils.getPathname(youTubeUrl).indexOf("/watch") === 0) {
+			youTubeId = Utils.getQueryValue(youTubeUrl, this.youTubeVideoIdQueryKey);
+			if (Utils.isNullOrUndefined(youTubeId)) {
+				return;
+			}
+		}
+
+		if (Utils.getPathname(youTubeUrl).indexOf("/embed") === 0) {
+			let youTubeIdMatch = youTubeUrl.match(/youtube\.com\/embed\/(\S+)/);
```
Comment (iconix) [inline src/scripts/domParsers/youtubeVideoExtractor.ts:28]: curious, why the switch from `\w` to `\S`?

File: src/scripts/domParsers/videoExtractor.ts [hunk 7]
```diff
@@ -0,0 +1,9 @@
+export interface VideoExtractor {
+	// Our 3 Domains all have the concept of a "VideoId" embedded somewhere in the page
```
Comment (iconix) [inline src/scripts/domParsers/videoExtractor.ts:2]: this isn't strictly true, right? YouTube.com doesn't have this concept

File: src/scripts/domParsers/videoExtractor.ts [hunk 8]
```diff
@@ -0,0 +1,9 @@
...
+	getVideoIds(pageUrl: string, pageContent: string): string[];
+
+	// We can use the video ideas to generate or retrieve src values that we can embed into our article preview
+	getVideoSrcValues(pageUrl: string, pageContent: string): string[];
```
Comment (iconix) [inline src/scripts/domParsers/videoExtractor.ts:6]: it's a little weird to me that we require passing both `pageUrl` and `pageContent` into this method, but only one or the other will get used, depending on which domain we're on... might it be better then to trust the caller to pass in the correct page info, and then just have a `pageInfo` (or similar) parameter?

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+
+export class KhanAcademyVideoExtractor implements VideoExtractor {
+	private youtubeExtractor: YoutubeVideoExtractor;
+
+	constructor() {
+		this.youtubeExtractor = new YoutubeVideoExtractor();
+	}
+
+	public getVideoIds(pageUrl: string, pageContent: string): string[] {
+		let regex = /id\s*=\s*("\s*video_(\S+)\s*"|'\s*video_(\S+)\s*')/gi;
```
Comment (iconix) [inline src/scripts/domParsers/khanAcademyVideoExtractor.ts:15]: I found this kind of bothersome to do while I was implementing Vimeo, but it will probably be useful for the future: could you add comments describing the regexes? :)

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts [hunk 10]
```diff
@@ -0,0 +1,50 @@
+import {VideoExtractor} from "./videoExtractor";
+import {VideoUtils} from "./videoUtils";
+import {YoutubeVideoExtractor} from "./youtubeVideoExtractor";
+
+import {Utils} from "../utils";
+
+export class KhanAcademyVideoExtractor implements VideoExtractor {
+	private youtubeExtractor: YoutubeVideoExtractor;
```
Comment (iconix) [inline src/scripts/domParsers/khanAcademyVideoExtractor.ts:8]: Something about this `KhanAcademyVideoExtractor` actually holding a `YoutubeVideoExtractor` makes me wonder: how about `KhanAcademyVideoExtractor extends YoutubeVideoExtractor`? 

I know it may feel kind of pointless because we'd override most of the `YoutubeVideoExtractor` method implementations... but hey, then `KhanAcademyVideoExtractor.createEmbeddedVideos` can call `super.createEmbeddedVideos` instead :D

More seriously, I also feel like using this pattern would make it quicker to grasp what's going on here

**Comment by iconix** [comment]
^Unless I'm missing something, you can't merge or update reviews :( So I'll just "Approve" in the old way:

LGTM :100: Thanks for tackling this bug! I like the cleanup that's been done to make things more reusable.

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+
+	constructor() {
+		this.youtubeExtractor = new YoutubeVideoExtractor();
+	}
+
+	public getVideoIds(pageUrl: string, pageContent: string): string[] {
```
Comment (mttwc) [inline src/scripts/domParsers/khanAcademyVideoExtractor.ts:14]: Thinking if we should rename pageContent to pageHtml across these methods for clarity

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts [hunk 12]
```diff
@@ -0,0 +1,50 @@
...
+		return VideoUtils.matchRegexFromPageContent(pageContent, regexes);
+	}
+
+	public getVideoSrcValues(pageUrl: string, pageContent: string): string[] {
+		if (Utils.isNullOrUndefined(pageContent)) {
+			return;
+		}
+
+		let videoIds = this.getVideoIds(pageUrl, pageContent);
+		if (Utils.isNullOrUndefined(videoIds)) {
```
Comment (mttwc) [inline src/scripts/domParsers/khanAcademyVideoExtractor.ts:27]: You could collapse these two if statements (the null/undefined check and the length check)

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts (hunk 10 above)
Comment (mttwc) [reply src/scripts/domParsers/khanAcademyVideoExtractor.ts:8]: Personally I prefer not using the extends and all those overrides because typescript currently doesn't support amazing support for safely overriding (i.e., it's easy for the dev to make a mistake such as forgetting to override something, or mispelling a method name). The thing I'd do would be to add a comment here saying that we use the same method as youtube to create embedded videos.

File: src/scripts/domParsers/vimeoVideoExtractor.ts [hunk 13]
```diff
@@ -0,0 +1,72 @@
...
+
+import {Utils} from "../utils";
+
+export class VimeoVideoExtractor implements VideoExtractor {
+	private dataOriginalSrcAttribute = "data-original-src";
+
+	/**
+	 * Return id for a video on Vimeo.com
+	 */
+	getVideoIds(pageUrl: string, pageContent: string): string[] {
```
Comment (mttwc) [inline src/scripts/domParsers/vimeoVideoExtractor.ts:13]: Add public keywords to this file for consistency?

File: src/scripts/domParsers/youtubeVideoExtractor.ts [hunk 14]
```diff
@@ -0,0 +1,75 @@
...
+
+export class YoutubeVideoExtractor implements VideoExtractor {
+	private youTubeWatchVideoBaseUrl = "https://www.youtube.com/watch";
+	private youTubeVideoIdQueryKey = "v";
+	private dataOriginalSrcAttribute = "data-original-src";
+
+	/**
+	 * Return the ID of the video in the YouTube URL as an array
+	 */
+	getVideoIds(youTubeUrl: string, pageContent: string): string[] {
```
Comment (mttwc) [inline src/scripts/domParsers/youtubeVideoExtractor.ts:14]: Same as above

**Review by mttwc — CHANGES_REQUESTED** [review]
Few minor comments. Nice refactor!

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts (hunk 10 above)
Comment (VishaalK) [reply src/scripts/domParsers/khanAcademyVideoExtractor.ts:8]: I left it as composition instead of inheritance because I don't think this follows the "is-a" rule of thumb. That being said, it doesn't really follow the "has-a" rule either :P. For inheritance, I also don't make use of a lot of the YouTube code and another good rule of thumb I've read about it is to avoid inheritance unless the vast majority of the code in the superclass is re-used.

File: src/scripts/domParsers/videoExtractor.ts (hunk 7 above)
Comment (VishaalK) [reply src/scripts/domParsers/videoExtractor.ts:2]: I'll correct this. Writing comments so hard -.-

File: src/scripts/domParsers/videoExtractor.ts (hunk 8 above)
Comment (VishaalK) [reply src/scripts/domParsers/videoExtractor.ts:6]: I considered passing in `PageInfo`. I will investigate if it easy enough to do. It would simplify the interface and make it a little more flexible.

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts (hunk 9 above)
Comment (VishaalK) [reply src/scripts/domParsers/khanAcademyVideoExtractor.ts:15]: Sure!

File: src/scripts/domParsers/vimeoVideoExtractor.ts (hunk 13 above)
Comment (VishaalK) [reply src/scripts/domParsers/vimeoVideoExtractor.ts:13]: Will do!

Edit: Done!

File: src/scripts/domParsers/youtubeVideoExtractor.ts (hunk 14 above)
Comment (VishaalK) [reply src/scripts/domParsers/youtubeVideoExtractor.ts:14]: Done!

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts (hunk 12 above)
Comment (VishaalK) [reply src/scripts/domParsers/khanAcademyVideoExtractor.ts:27]: Done!

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts (hunk 11 above)
Comment (VishaalK) [reply src/scripts/domParsers/khanAcademyVideoExtractor.ts:14]: Do you think we should pipe `pageInfo` through from `clipper.tsx` -> `augmentationHelper.ts` to all  this extraction stuff?

File: src/scripts/domParsers/youtubeVideoExtractor.ts (hunk 6 above)
Comment (VishaalK) [reply src/scripts/domParsers/youtubeVideoExtractor.ts:28]: Some of the videos on KhanAcademy have hyphens in their data-ids, and `\w` does not cover those. Since they are also YouTube vids I changed the youtube regexes as well.

File: src/scripts/domParsers/videoExtractor.ts (hunk 7 above)
Comment (VishaalK) [reply src/scripts/domParsers/videoExtractor.ts:2]: I corrected it by deleting the comment

File: src/scripts/domParsers/khanAcademyVideoExtractor.ts (hunk 11 above)
Comment (mttwc) [reply src/scripts/domParsers/khanAcademyVideoExtractor.ts:14]: I don't think so. I would love to keep this as seperate as possible from the clipper world (pageInfo has a reference to ONApi)
