### PR TITLE
[Bug] Change logic of when tooltip shows + clean up a bit of the logic

### LINKED ISSUE #39: Tooltips are showing too often
There is currently no way to taper off how often the tooltip shows.

Mitigation is to give users an option to turn them off and turn them off after they've been seen a certain times and if the user has ever clipped the content type we are trying to inform them about.

### PR DESCRIPTION
**Pull request by VishaalK**
Changed logic to:
1. If a user has ever clipped this content type, do not show the tooltip
2. If a user has seen this tooltip in the last 21 days, do not show the tooltip
3. If a user has seen ANY OTHER tooltip in the last 7 days, do not show the tooltip (to prevent seeing 4 tooltips when hopping page to page)
4. If a user has seen a tooltip 3 or more times, never show the tooltip

There will be another PR when design gets back to us about letting users turn it off.

Resolves #39 

As for logic cleanup, now instead of iterating through each `TooltipType` and checking against all the regexes and delays, if a page matches a content type and the delay is over `shouldShowTooltip(...)` returns that `TooltipType` and then we show it.

### CODE REVIEW

File: src/scripts/constants.ts [hunk 1]
```diff
@@ -323,7 +323,9 @@ export module Constants {
 	}
 
 	export module Settings {
-		export var timeBetweenTooltips = 1000 * 60 * 60 * 24 * 7 * 3; // 21 days
+		export var timeBetweenDifferentTooltips = 1000 * 60 * 60 * 24 * 7 * 1; // 21 days
```
Comment (mttwc) [inline src/scripts/constants.ts]: Comment should say // 7 days

File: src/scripts/extensions/bookmarklet/inlineExtension.ts [hunk 2]
```diff
@@ -48,8 +48,8 @@ export class InlineExtension extends ExtensionBase<InlineWorker, any, any> {
 	protected addPageNavListener(callback: (tab: any) => void) {
 	}
 
-	protected checkIfTabMatchesATooltipType(tab: SafariBrowserTab, tooltipType: TooltipType): boolean {
-		return false;
+	protected checkIfTabMatchesATooltipType(tab: SafariBrowserTab, tooltipTypes: TooltipType[]): TooltipType {
```
Comment (mttwc) [inline src/scripts/extensions/bookmarklet/inlineExtension.ts:51]: This may not have anything to do with your changes ... but do you know why the tab's type here is SafariBrowserTab, given that this is bookmarklet code?

File: src/scripts/extensions/extensionBase.ts [hunk 3]
```diff
@@ -274,16 +274,26 @@ export abstract class ExtensionBase<TWorker extends ExtensionWorkerBase<TTab, TT
 		});
 	}
 
-	private shouldShowTooltip(tab: TTab, tooltipType: TooltipType): boolean {
-		if (this.tooltip.tooltipDelayIsOver(tooltipType, Date.now()) && this.checkIfTabMatchesATooltipType(tab, tooltipType)) {
-			return true;
+	private shouldShowTooltip(tab: TTab, tooltipTypes: TooltipType[]): TooltipType {
+		let type = this.checkIfTabMatchesATooltipType(tab, tooltipTypes);
+
+		// If the tab doesn't match any of the given tooltipTypes, then return
```
Comment (mttwc) [inline src/scripts/extensions/extensionBase.ts]: This comment seems uneccessary

File: src/scripts/extensions/tooltipHelper.ts [hunk 4]
```diff
@@ -33,22 +35,38 @@ export class TooltipHelper {
...
+		}
+
+		// If the user has seen enough of our tooltips :P 
+		if (numTimesTooltipHasBeenSeen >= Constants.Settings.maximumNumberOfTimesToShowTooltips) {
+			return false;
+		}
 
-		let isTooltipShownDelayOver = (time - lastSeenTooltipTime) >= timeBetweenTooltips;
-		let isClipDelayOver = (time - lastSeenClipTime) >= timeBetweenTooltips;
+		// If it has been less than 3 weeks since the user saw this specific tooltip, return false
```
Comment (mttwc) [inline src/scripts/extensions/tooltipHelper.ts]: We shouldn't have comments with actual time numbers in them as they might get changed, and we might forget to update these. The values in the constants file should be enough

File: src/scripts/extensions/tooltipHelper.ts [hunk 5]
```diff
@@ -33,22 +35,38 @@ export class TooltipHelper {
...
 	}
 
-	public tooltipDelayIsOver(tooltipType: TooltipType, time: number) {
-		if (Utils.isNullOrUndefined(tooltipType) || Utils.isNullOrUndefined(time)) {
+	public tooltipDelayIsOver(tooltipType: TooltipType, curTime: number): boolean {
+		if (Utils.isNullOrUndefined(tooltipType) || Utils.isNullOrUndefined(curTime)) {
 			throw new Error("Invalid argument passed to tooltipDelayIsOver");
 		}
 
+		let numTimesTooltipHasBeenSeen = this.getTooltipInformation(ClipperStorageKeys.numTimesTooltipHasBeenSeenBase, tooltipType);
```
Comment (mttwc) [inline src/scripts/extensions/tooltipHelper.ts]: I think the variable declarations here can be moved to right before they are used in each of the preceeding if statements for readability.

File: src/scripts/extensions/tooltipHelper.ts [hunk 6]
```diff
@@ -33,22 +35,38 @@ export class TooltipHelper {
...
-		let isClipDelayOver = (time - lastSeenClipTime) >= timeBetweenTooltips;
+		// If it has been less than 3 weeks since the user saw this specific tooltip, return false
+		if (this.tooltipHasBeenSeenInLastTimePeriod(tooltipType, curTime, Constants.Settings.timeBetweenSameTooltip)) {
+			return false;
+		}
 
-		// Only shows if it has been >= 3 weeks since the User saw a tooltip AND it has been >= 3 weeks
-		// since their last Clip of this specific TooltipType
-		return isTooltipShownDelayOver && isClipDelayOver;
+		// If it has been less than 7 days since the user saw any tooltip, then return false
```
Comment (mttwc) [inline src/scripts/extensions/tooltipHelper.ts]: You might want consider moving each of these logical blocks into small (private) methods for readability ala. Clean Code style.

File: src/tests/extensions/tooltipHelper_tests.ts [hunk 7]
```diff
@@ -109,63 +110,109 @@ test("Null or undefined passed to tooltipDelayIsOver should throw an Error", ()
...
 
-test("tooltipDelayIsOver should return true when they haven't clipped in 21 days and the key for lastSeenTime is empty", () => {
-	setClipTimeOutsideOfRange();
-	strictEqual(tooltipHelper.tooltipDelayIsOver(testType, baseDate.getTime()), true);
+test("tooltipHasBeenSeenInLastTimePeriod should return TRUE when a value is in storage and is within the time period", () => {
+	setSeenTimeWithinRange(testType, Constants.Settings.timeBetweenSameTooltip);
+	ok(tooltipHelper.tooltipHasBeenSeenInLastTimePeriod(testType, baseTime, Constants.Settings.timeBetweenSameTooltip));
+});
+
+test("hasAnyTooltipBeenSeenInLastTimerPeriod should return FALSE when nothing is in storage", () => {
```
Comment (mttwc) [inline src/tests/extensions/tooltipHelper_tests.ts]: nit: typo

**Comment by mttwc** [comment]
Nice change! Just some minor readability/formatting suggestions :)

File: src/scripts/constants.ts (hunk 1 above)
Comment (leakymemory) [inline src/scripts/constants.ts]: Should the comment on this say `// 1 week`?

File: src/scripts/constants.ts [hunk 8]
```diff
@@ -323,7 +323,9 @@ export module Constants {
...
+		export var timeBetweenSameTooltip = 1000 * 60 * 60 * 24 * 7 * 3; // 7 days
```
Comment (leakymemory) [inline src/scripts/constants.ts]: And this one `// 3 weeks`?

**Comment by leakymemory** [comment]
Agreed. This makes the logic read much cleaner.

**Review by mttwc — APPROVED** [review]

File: src/scripts/constants.ts (hunk 1 above)
Comment (VishaalK) [reply src/scripts/constants.ts]: Done!

File: src/scripts/constants.ts (hunk 8 above)
Comment (VishaalK) [reply src/scripts/constants.ts]: Done!

File: src/scripts/constants.ts (hunk 1 above)
Comment (VishaalK) [reply src/scripts/constants.ts]: Done! Made it 1 week

File: src/scripts/extensions/bookmarklet/inlineExtension.ts (hunk 2 above)
Comment (VishaalK) [reply src/scripts/extensions/bookmarklet/inlineExtension.ts:51]: I am not sure. I followed the type on `geUniqueId(): SafariBrowserTab`.

File: src/scripts/extensions/extensionBase.ts (hunk 3 above)
Comment (VishaalK) [reply src/scripts/extensions/extensionBase.ts]: Removed!

File: src/scripts/extensions/tooltipHelper.ts (hunk 5 above)
Comment (VishaalK) [reply src/scripts/extensions/tooltipHelper.ts]: Done-zo

File: src/scripts/extensions/tooltipHelper.ts (hunk 4 above)
Comment (VishaalK) [reply src/scripts/extensions/tooltipHelper.ts]: I made the comments more generic!

File: src/scripts/extensions/tooltipHelper.ts (hunk 6 above)
Comment (VishaalK) [reply src/scripts/extensions/tooltipHelper.ts]: I think they are readable enough. While its a low level of implementation all the blocks are at the same level.

File: src/tests/extensions/tooltipHelper_tests.ts (hunk 7 above)
Comment (VishaalK) [reply src/tests/extensions/tooltipHelper_tests.ts]: Done!
