### PR TITLE
Bug/safari crash on signout

### LINKED ISSUE #129: MacOS: Clicking "Sign Out" is causing Safari to crash
No idea what might be causing this, but it seems that the popup window we launch to navigate to the sign-out URL is somehow causing Safari to crash.  This happens consistently on my Macbook.

Here's the crash callstack:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.Safari.framework      0x00007fff9549dcdd Safari::BrowserPageNavigationClient::didFailNavigation(Safari::WK::Page const&, WKNavigation*, NSError*, Safari::WK::Type const&) + 87
1   com.apple.Safari.framework      0x00007fff956d4a5f Safari::WK::didFailNavigation(OpaqueWKPage const*, OpaqueWKNavigation const*, OpaqueWKError const*, void const*, void const*) + 122
2   com.apple.WebKit                0x00007fff8d095581 WKPageSetPageNavigationClient::NavigationClient::didFailNavigationWithError(WebKit::WebPageProxy&, WebKit::WebFrameProxy&, API::Navigation*, WebCore::ResourceError const&, API::Object*) + 269
3   com.apple.WebKit                0x00007fff8cfebeaa WebKit::WebPageProxy::didFailLoadForFrame(unsigned long long, unsigned long long, WebCore::ResourceError const&, WebKit::UserData const&) + 332
4   com.apple.WebKit                0x00007fff8d001db2 void IPC::handleMessage<Messages::WebPageProxy::DidFailLoadForFrame, WebKit::WebPageProxy, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WebCore::ResourceError const&, WebKit::UserData const&)>(IPC::MessageDecoder&, WebKit::WebPageProxy*, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WebCore::ResourceError const&, WebKit::UserData const&)) + 165
5   com.apple.WebKit                0x00007fff8cebf777 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::MessageDecoder&) + 129
6   com.apple.WebKit                0x00007fff8d03f5a0 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::MessageDecoder&) + 24
7   com.apple.WebKit                0x00007fff8ce8bd29 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::MessageDecoder, std::__1::default_delete<IPC::MessageDecoder> >) + 119
8   com.apple.WebKit                0x00007fff8ce8e6d6 IPC::Connection::dispatchOneMessage() + 126
9   com.apple.JavaScriptCore        0x00007fff87acd4ad WTF::RunLoop::performWork() + 333
10  com.apple.JavaScriptCore        0x00007fff87acd622 WTF::RunLoop::performWork(void*) + 34
11  com.apple.CoreFoundation        0x00007fff84ca9551 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
12  com.apple.CoreFoundation        0x00007fff84c8a6bd __CFRunLoopDoSources0 + 557
13  com.apple.CoreFoundation        0x00007fff84c89bb6 __CFRunLoopRun + 934
14  com.apple.CoreFoundation        0x00007fff84c895b4 CFRunLoopRunSpecific + 420
15  com.apple.HIToolbox             0x00007fff8422af6c RunCurrentEventLoopInMode + 240
16  com.apple.HIToolbox             0x00007fff8422ada1 ReceiveNextEventCommon + 432
17  com.apple.HIToolbox             0x00007fff8422abd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
18  com.apple.AppKit                0x00007fff829215f5 _DPSNextEvent + 1093
19  com.apple.AppKit                0x00007fff830318eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
20  com.apple.Safari.framework      0x00007fff9541c771 -[BrowserApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 252
21  com.apple.AppKit                0x00007fff82915fbd -[NSApplication run] + 926
22  com.apple.AppKit                0x00007fff828e0a8a NSApplicationMain + 1237
23  libdyld.dylib                   0x00007fff99cc9255 start + 1
```

### PR DESCRIPTION
**Pull request by leakymemory**
Fixes #129 

On clipper sign-out, we were listening for the response URL and then manually closing the popup window.  However, it looks like on sign-out, this isn't necessary as the window gets closed automatically.

This causes a problem because the listener we set up gets called and tries to access the newWindow object, which is now null.  In pre-Sierra versions of Safari this seemed to be ok, but in Sierra it now causes the browser to crash.

### CODE REVIEW

File: src/scripts/extensions/safari/safariWorker.ts [hunk 1]
```diff
@@ -129,34 +129,37 @@ export class SafariWorker extends ExtensionWorkerBase<SafariBrowserTab, SafariBr
...
-			};
-			newWindow.addEventListener("navigate", redirectListener);
-
-			let closeListener = (event) => {
-				errorObject ? reject(errorObject) : resolve(redirectOccurred);
-				newWindow.removeEventListener(closeListener);
-			};
-			newWindow.addEventListener("close", closeListener);
+						newWindow.removeEventListener(redirectListener);
+						newWindow.close();
```
Comment (mttwc) [inline src/scripts/extensions/safari/safariWorker.ts]: Shouldn't we wrap the new if statement around the .close() call? That way we still get our error reporting.

**Comment by mttwc** [comment]
Just a question above.

File: src/scripts/extensions/safari/safariWorker.ts (hunk 1 above)
Comment (leakymemory) [reply src/scripts/extensions/safari/safariWorker.ts]: Yeah, I thought about that, though in the waitForClose option implies that we cannot monitor the results of the call (that or we don't care).  That being said, let me look at it again and see if it makes sense to still include the event listeners.

**Comment by mttwc** [comment]
Would love to walk through this code on the non-Sierra machine with you today if possible. I want to understand this change a bit more.

File: src/scripts/extensions/safari/safariWorker.ts [hunk 2]
```diff
@@ -129,34 +129,39 @@ export class SafariWorker extends ExtensionWorkerBase<SafariBrowserTab, SafariBr
...
-				errorObject ? reject(errorObject) : resolve(redirectOccurred);
-				newWindow.removeEventListener(closeListener);
-			};
-			newWindow.addEventListener("close", closeListener);
+				newWindow.addEventListener("close", (event) => {
+					errorObject ? reject(errorObject) : resolve(redirectOccurred);
+				});
+			}
+
+			newWindow.activeTab.url = url;
```
Comment (mttwc) [inline src/scripts/extensions/safari/safariWorker.ts:164]: Nice. It makes way more sense for this line to be at the end when all the listeners have been attached. Not doing this in the past for things like setting img urls and whatnot has led to some hard-to-catch bugs, so we should continue to watch out for these in the future :)

Comment (leakymemory) [reply src/scripts/extensions/safari/safariWorker.ts:164]: Agreed.
